# Generated by Django 5.0.3 on 2024-03-22 20:13

import dds_registration.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default=dds_registration.models.random_code, unique=True)),
                ('title', models.TextField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(default=False)),
                ('registration_open', models.DateField(auto_now_add=True, help_text='Date registration opens')),
                ('registration_close', models.DateField(blank=True, help_text='Date registration closes', null=True)),
                ('max_participants', models.PositiveIntegerField(default=0, help_text='Maximum number of participants to this event (0 = no limit)')),
                ('currency', models.TextField(blank=True, null=True)),
                ('payment_deadline_days', models.IntegerField(default=30)),
                ('payment_details', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default=functools.partial(dds_registration.models.random_code, *(), **{'length': 4}))),
                ('only_registration', models.BooleanField(default=True)),
                ('percentage', models.IntegerField(blank=True, help_text='Value as a percentage, like 10', null=True)),
                ('absolute', models.FloatField(blank=True, help_text='Absolute amount of discount', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dds_registration.event')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_registration', models.BooleanField(default=True)),
                ('percentage', models.IntegerField(blank=True, help_text='Value as a percentage, like 10', null=True)),
                ('absolute', models.FloatField(blank=True, help_text='Absolute amount of discount', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dds_registration.event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dds_registration.event')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('add_on', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dds_registration.event')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('invoice_no', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('payment_method', models.TextField(choices=[('STRIPE', 'Stripe'), ('INVOICE', 'Invoice')], default='STRIPE')),
                ('extra_invoice_text', models.TextField(blank=True, default='')),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='dds_registration.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('options', models.ManyToManyField(to='dds_registration.registrationoption')),
            ],
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('event', 'user'), name='Single active registration'),
        ),
    ]
