# Generated by Django 5.0.3 on 2024-03-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='Single registration',
        ),
    ]
