# Generated by Django 5.0.3 on 2024-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.TextField(choices=[('STRIPE', 'Stripe'), ('INVOICE', 'Invoice')], default='STRIPE'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.TextField(choices=[('CREATED', 'Created'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='CREATED'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='template',
            field=models.TextField(choices=[('M-CHF', 'Membership - Swiss Francs'), ('M-EUR', 'Membership - Euros'), ('G-USD', 'Generic - USD'), ('G-CHF', 'Generic - CHF'), ('G-EUR', 'Generic - EUR'), ('G-CAD', 'Generic - CAD')], default='M-CHF'),
        ),
    ]
