# Generated by Django 5.0.3 on 2024-03-26 00:50

import dds_registration.core.helpers.dates
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_close',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date registration closes (inclusive)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_open',
            field=models.DateField(auto_now_add=True, help_text='Date registration opens (inclusive)'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.IntegerField(default=dds_registration.core.helpers.dates.this_year)),
                ('honorary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
