# Generated by Django 5.0.3 on 2024-03-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationoption',
            name='item',
            field=models.CharField(max_length=40),
        ),
    ]
