# Generated by Django 5.0.3 on 2024-03-27 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.TextField(choices=[('NORMAL', 'Normal'), ('BOARD', 'Board member'), ('HONORARY', 'Honorary'), ('BUSINESS', 'Business'), ('ACADEMIC', 'Academic')], default='NORMAL'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='dds_registration.invoice'),
        ),
    ]
