# Generated by Django 5.0.3 on 2024-03-25 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_close',
            field=models.DateField(blank=True, help_text='Date registration closes (inclusive)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_open',
            field=models.DateField(auto_now_add=True, help_text='Date registration opens (inclusive)'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('honorary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
