# Generated by Django 5.0.3 on 2024-03-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0002_alter_registrationoption_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.TextField(choices=[('NORMAL', 'Normal'), ('BOARD', 'Board member'), ('HONORARY', 'Honorary'), ('BUSINESS', 'Business')], default='NORMAL'),
        ),
    ]
