# Generated by Django 5.0.3 on 2024-03-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0002_event_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_public',
            new_name='public',
        ),
    ]
