# Generated by Django 5.0.3 on 2024-04-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0002_remove_event_refund_window_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.TextField(choices=[('STRIPE', 'Credit Card (Stripe - costs 2-4% more due to credit card fees)'), ('INVOICE', 'Bank Transfer (Invoice)')], default='INVOICE'),
        ),
    ]
