# Generated by Django 5.0.3 on 2024-03-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0002_alter_membership_membership_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='Single registration per verified user account',
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'WITHDRAWN'), _negated=True), fields=('event', 'user'), name='Single registration per verified user account'),
        ),
    ]
