# Generated by Django 5.0.3 on 2024-03-26 15:23

import dds_registration.core.helpers.dates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0002_alter_event_registration_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_type',
            field=models.TextField(choices=[('NORMAL_CREDIT_CARD', 'Normal membership - Pay by credit card'), ('NORMAL_INVOICE', 'Normal membership - Pay by invoice'), ('ACADEMIC_CREDIT_CARD', 'Academic membership - Pay by credit card'), ('ACADEMIC_INVOICE', 'Academic membership - Pay by invoice')], default='NORMAL_CREDIT_CARD'),
        ),
        migrations.AddField(
            model_name='membership',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='until',
            field=models.IntegerField(default=dds_registration.core.helpers.dates.this_year),
        ),
    ]
