# Generated by Django 5.0.3 on 2024-03-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0003_invoice_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='template',
        ),
    ]
