# Generated by Django 5.0.3 on 2024-04-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0003_registration_send_update_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='mailing_list',
            field=models.BooleanField(default=False),
        ),
    ]
