# Generated by Django 5.0.3 on 2024-03-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0003_registration_single_active_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_open',
            field=models.DateField(auto_now_add=True, help_text='Date registration opens'),
        ),
    ]
