# Generated by Django 5.0.3 on 2024-04-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0004_membership_mailing_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='refund_last_day',
            field=models.DateField(blank=True, help_text='Last day that a fee refund can be offered', null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dds_registration.payment'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='dds_registration.registrationoption'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dds_registration.payment'),
        ),
    ]
