# Generated by Django 5.0.3 on 2024-04-01 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0005_membership_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dds_registration.invoice'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='dds_registration.invoice'),
        ),
    ]
