# Generated by Django 5.0.3 on 2024-04-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0005_alter_event_refund_last_day_alter_membership_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
