# Generated by Django 5.0.3 on 2024-04-30 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0006_message_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='dds_registration.registrationoption'),
        ),
    ]
