# Generated by Django 5.0.3 on 2024-04-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0006_alter_membership_invoice_alter_registration_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='currency',
        ),
    ]
