# Generated by Django 5.0.3 on 2024-06-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0007_event_free_alter_registration_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='for_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dds_registration.event'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('event__isnull', True), ('for_members', True)), models.Q(('event__isnull', False), ('for_members', False)), _connector='OR'), name='either_event_or_for_members'),
        ),
    ]
