# Generated by Django 5.0.3 on 2024-06-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0008_message_for_members_alter_message_event_and_more'),
        ('djf_surveys', '0013_survey_success_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='application_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='for_event', to='djf_surveys.survey'),
        ),
        migrations.AddField(
            model_name='registration',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='djf_surveys.useranswer'),
        ),
    ]
