# Generated by Django 5.0.3 on 2024-06-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0009_event_application_form_registration_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='application_submitted_email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
