# Generated by Django 5.0.3 on 2024-06-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0011_event_application_accepted_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='application_rejected_email',
            field=models.TextField(blank=True, help_text='The email sent when an application is rejected', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='application_accepted_email',
            field=models.TextField(blank=True, help_text='The email sent when an application is accepted and registration can proceed', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='application_submitted_email',
            field=models.TextField(blank=True, help_text='The email sent when the application is submitted', null=True),
        ),
    ]
