# Generated by Django 5.0.3 on 2024-07-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0013_event_credit_cards_event_vat_rate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('credit_cards', True), ('vat_rate__isnull', True)), models.Q(('credit_cards', False), ('vat_rate__isnull', False)), _connector='OR'), name='no_vat_for_credit_cards'),
        ),
    ]
