# Generated by Django 5.0.3 on 2024-07-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0015_event_members_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationoption',
            name='membership_end_year',
            field=models.IntegerField(default=False, help_text='If membership is included, until what year is it valid? Leave blank for current year.'),
        ),
        migrations.AlterField(
            model_name='registrationoption',
            name='includes_membership',
            field=models.BooleanField(default=False, help_text='Does this registration option include DdS membership?'),
        ),
    ]
