# Generated by Django 5.0.3 on 2024-07-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0016_registrationoption_membership_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationoption',
            name='membership_end_year',
            field=models.IntegerField(blank=True, help_text='If membership is included, until what year is it valid? Leave blank for current year.'),
        ),
    ]
