# Generated by Django 5.0.3 on 2024-09-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0018_remove_message_either_event_or_for_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='application_close',
            field=models.DateField(help_text='Date applications close (inclusive)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='application_open',
            field=models.DateField(auto_now_add=True, help_text='Date applications open (inclusive)', null=True),
        ),
    ]
