# Generated by Django 5.0.3 on 2024-09-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0019_event_application_close_event_application_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationoption',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of participants (0 = no limit)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='application_open',
            field=models.DateField(help_text='Date applications open (inclusive)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_open',
            field=models.DateField(help_text='Date registration opens (inclusive)'),
        ),
    ]
