# Generated by Django 5.0.3 on 2024-09-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0020_registrationoption_max_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='data',
            field=models.JSONField(default=dict, help_text='JSON object'),
        ),
    ]
