# Generated by Django 5.0.3 on 2025-02-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0021_alter_payment_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationoption',
            name='currency',
            field=models.TextField(choices=[('USD', 'US Dollar'), ('CHF', 'Swiss Franc'), ('EUR', 'Euro'), ('CAD', 'Canadian Dollar'), ('SGD', 'Singaporean Dollar')], default='EUR'),
        ),
    ]
