# Generated by Django 5.0.3 on 2025-03-31 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0022_alter_registrationoption_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_text',
            field=models.TextField(blank=True, help_text='Certificate text. Can include MarkDown. MUST include `{attendee_name}` template variable where the name of the attendee will be substituted.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_title',
            field=models.TextField(blank=True, help_text='Certificate title.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='dds_registration.registration')),
            ],
        ),
    ]
