# Generated by Django 5.0.3 on 2025-03-31 21:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_registration', '0023_event_certificate_text_event_certificate_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_invitation',
            field=models.BooleanField(default=False, help_text='Event has letter of invitation'),
        ),
        migrations.AddField(
            model_name='event',
            name='invitation_text',
            field=models.TextField(blank=True, help_text='Invitation letter text. Can include MarkDown. MUST include `{attendee_name}` template variable where the name of the attendee will be substituted.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='invitation_title',
            field=models.TextField(blank=True, help_text='Invtation letter title.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_certificate',
            field=models.BooleanField(default=False, help_text='Event has certificate of participation'),
        ),
        migrations.CreateModel(
            name='InvitationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='dds_registration.registration')),
            ],
        ),
    ]
